import "./load-env.js";

export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
export const YANDEX_CLIENT_ID = process.env.YANDEX_CLIENT_ID;
export const YANDEX_CLIENT_SECRET = process.env.YANDEX_CLIENT_SECRET;
export const VK_CLIENT_ID = process.env.VK_CLIENT_ID;
export const VK_CLIENT_SECRET = process.env.VK_CLIENT_SECRET;
export const SBER_CLIENT_ID = process.env.SBER_CLIENT_ID;
export const SBER_CLIENT_SECRET = process.env.SBER_CLIENT_SECRET;
export const MTS_CLIENT_ID = process.env.MTS_CLIENT_ID;
export const MTS_CLIENT_SECRET = process.env.MTS_CLIENT_SECRET;
export const GOOGLE_APPLICATION_CREDENTIALS = process.env.GOOGLE_APPLICATION_CREDENTIALS;
export const YANDEX_API_KEY = process.env.YANDEX_API_KEY;
export const YANDEX_FOLDER_ID = process.env.YANDEX_FOLDER_ID;
export const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
export const YOOKASSA_SHOP_ID = process.env.YOOKASSA_SHOP_ID;
export const YOOKASSA_SECRET_KEY = process.env.YOOKASSA_SECRET_KEY;
export const SMTP_PASSWORD = process.env.SMTP_PASSWORD;
export const EMAIL_OTP_SECRET = process.env.EMAIL_OTP_SECRET;
export const YANDEX_METRIKA_API_TOKEN = process.env.YANDEX_METRIKA_API_TOKEN;
