import crypto from "node:crypto";
import pg from "pg";
import { getPool, query } from "../db/index.js";

let intentLockPool;
export async function acquireFileIntentLock(id, { tryOnly = false } = {}) {
  intentLockPool ||= new pg.Pool({ ...getPool().options, max: 8, connectionTimeoutMillis: 2000, allowExitOnIdle: true });
  const client = await intentLockPool.connect();
  try {
    const result = await client.query(`select ${tryOnly ? "pg_try_advisory_lock" : "pg_advisory_lock"}(731243, hashtext($1)) as locked`, [String(id)]);
    if (tryOnly && !result.rows[0].locked) { client.release(); return null; }
  } catch (error) { client.release(true); throw error; }
  let released = false;
  return async () => {
    if (released) return;
    released = true;
    try { await client.query("select pg_advisory_unlock(731243, hashtext($1))", [String(id)]); client.release(); }
    catch { client.release(true); }
  };
}

// Paths must be validated/generated by the writer before calling this method.
// This INSERT commits on its own, before the filesystem or claim transaction.
export async function beginFileIntent({ id = crypto.randomUUID(), kind, guestSessionId = null, guestDocumentId = null,
  userId = null, sourcePath = null, destinationPath, temporaryPath = null, createdAt = new Date(), expiresAt }) {
  const release = await acquireFileIntentLock(id);
  try {
    const result = await query(`insert into guest_file_intents
      (id, kind, guest_session_id, guest_document_id, user_id, source_path, destination_path, temporary_path, created_at, expires_at)
      values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,
    [id, kind, guestSessionId, guestDocumentId, userId, sourcePath, destinationPath, temporaryPath, createdAt, expiresAt]);
    return { ...result.rows[0], release };
  } catch (error) { await release(); throw error; }
}

export async function cancelFileIntent(id) {
  await query("update guest_file_intents set cancelled_at = now() where id = $1", [id]);
}

export async function attachUploadIntent(id, document) {
  await query("update guest_file_intents set guest_document_id = $2, expires_at = $3 where id = $1",
    [id, document.id, document.expires_at]);
}

export async function closeFileIntentLocks() {
  if (intentLockPool) await intentLockPool.end();
  intentLockPool = null;
}
